name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./@hexlet/code
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run linter
        run: make lint
      - name: Install dependencies
        run: npm ci
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}